config/routes.rb
Rails.application.routes.draw do

 # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
 
 namespace :admin do
    get '/' => 'homes#top'
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :categories, only: [:index, :create, :edit, :update, :destroy]
    resources :users, only: [:show, :edit, :update, :destroy]
    resources :posts, only: [:show, :destroy] do
      resources :reviews, only: [:index, :destroy]
    end
    
    get 'search' => 'searches#search'
  end
  
 # 会員用
  devise_for :user, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :user do
    post 'user/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  
  scope module: :public do
    root to: 'homes#top'  
    resources :posts, only: [:new, :index, :show, :edit, :create, :update, :destroy] do
      resource :likes, only: [:create, :destroy]
      resources :reviews, only: [:new, :index, :create], shallow: true do
        resource :favorite, only: [:create, :destroy]
      end
      resources :reviews, only: [:edit, :update, :destroy]
    end 
    
    resources :retirements, only: [:new, :destroy]
    resources :users, except: [:show, :edit, :update] do
      member do
        get :likes
      end
    end
    
    get 'search' => 'searches#search'
    get '/:name' => 'users#show' 
    get '/:name/edit' => 'users#edit'
    patch '/:name' => 'users#update'
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < ApplicationController
  before_action :authenticate_admin!
  
  def search
    @range = params[:range]
    @word = params[:word]
    @method = params[:method]
    if @range == "User"
      @users = User.looks(@word, @method)
    else
      @posts = Post.looks(@word, @method)
    end
  end
  
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/views/admin/searches/search.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-sm-12 mx-2 mx-sm-auto">
    <h3 class="pl-3 pt-3" style="color: #3a5b52;">"<%= @word %>"の検索結果</h3>
       
    <table class="table">
      <% if @range == "User" %>
        <thead>
          <tr>
            <th></th>
            <th>ユーザー</th>
          </tr>  
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= link_to admin_user_path(user.id) do %>
                  <%= image_tag user.get_profile_image(100,100) %>
                <% end %>  
              </td>
              <td><%= link_to user.name, admin_user_path(user.id), class: "text-dark" %></td>
            </tr>
          <% end %>
        </tbody>
      
      <% else %>
        <thead>
          <tr>
            <th></th>
            <th>展覧会名</th>
            <th>ユーザー</th>
          </tr>
        </thead>
        <tbody>
          <% @posts.each do |post| %>
            <tr>
              <td>
                <%= link_to admin_post_path(post.id) do %>
                  <%= image_tag post.get_post_image(100,142) %>
                <% end %>  
              </td>
              <td><%= link_to post.name, admin_post_path(post.id), class: "text-dark" %></td>
              <td><%= link_to post.user.name, admin_user_path(post.user.id), class: "text-dark" %></td>
            </tr>
          <% end %>  
        </tbody>
      <% end %>
    </table>
      
  </div>
</div>  
            