config/routes.rb
Rails.application.routes.draw do

 # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
 
 namespace :admin do
    get '/' => 'homes#top'
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :categories, only: [:index, :create, :edit, :update, :destroy]
    resources :users, only: [:show, :edit, :update, :destroy]
    resources :posts, only: [:show, :destroy] do
      resources :reviews, only: [:index, :destroy]
    end
    
    get 'search' => 'searches#search'
  end
  
 # 会員用
  devise_for :user, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :user do
    post 'user/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  
  scope module: :public do
    root to: 'homes#top'  
    resources :posts, only: [:new, :index, :show, :edit, :create, :update, :destroy] do
      resource :likes, only: [:create, :destroy]
      resources :reviews, only: [:new, :index, :create], shallow: true do
        resource :favorite, only: [:create, :destroy]
      end
      resources :reviews, only: [:edit, :update, :destroy]
    end 
    
    resources :retirements, only: [:new, :destroy]
    resources :users, except: [:show, :edit, :update] do
      member do
        get :likes
      end
    end
    
    get 'search' => 'searches#search'
    get '/:name' => 'users#show' 
    get '/:name/edit' => 'users#edit'
    patch '/:name' => 'users#update'
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :post_categories, dependent: :destroy
  has_many :posts, through: :post_categories, dependent: :destroy
  
  validates :name, uniqueness: true, length: { in: 1..30 }
  
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_categories, only: [:edit, :update]
   
  def index
    @category = Category.new
    @categories = Category.all
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "登録に成功しました"
      redirect_to admin_categories_path
    else
      flash.now[:alert] = "登録に失敗しました"
      @categories = Category.all
      render :index
    end
  end

  def edit
  end
  
  def update
    if @category.update(category_params)
      flash[:notice] = "変更が保存されました"
      redirect_to admin_categories_path
    else
      render :edit
    end
  end
  
  def destroy
    category = Category.find(params[:id])
    if category.destroy
      flash[:notice] = "削除に成功しました"
      redirect_to admin_categories_path
    else
      render :index
    end
  end
  
  private
  
  def set_categories
    @category = Category.find(params[:id])
  end  
  
  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<div class="container">
  <div class="row">
    <h2 class="pl-3 pt-3" style="color: #3a5b52;">カテゴリー編集</h2>
    <div class="col-md-6 col-sm-12 mx-2 mx-sm-auto">
     
      <% if @category.errors.any? %>
        <%= @category.errors.count %>件のエラーが発生しました
        <ul>
          <% @category.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      
      <%= form_with model: @category, url: admin_category_path(@category.id), local:true do |f| %>
        <div class="d-flex">
          <div class="m-2"><%= f.text_field :name %></div>
          <div class="m-2"><%= f.submit '変更を保存', class: "btn btn-outline-success btn-lg" %></div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/categories/index.html.erb
<div class="container">
  <div class="row">
    <h2 class="pl-3 pt-3" style="color: #3a5b52;">カテゴリー作成・一覧</h2>
    <div class="col-md-6 col-sm-12 mx-2 mx-sm-auto">
      
      <% if @category.errors.any? %>
        <%= @category.errors.count %>件のエラーが発生しました
        <ul>
          <% @category.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      
      <!--カテゴリー新規登録 -->
      <%= form_with model: @category, url: admin_categories_path, method: :post, local:true do |f| %>
        <div class="d-flex">
          <div class="m-2"><%= f.text_field :name, placeholder: "絵画" %></div>
          <div class="m-2"><%= f.submit '登録', class: "btn btn-outline-success btn-lg" %></div>
        </div>
      <% end %>

      <!--カテゴリー　一覧 -->
      <h6 class="pt-4" style="color: #3a5b52;">カテゴリー一覧</h6>
      <% @categories.each do |category| %>
        <div class="d-flex">
          <div class="m-2"><%= category.name %></div>
          <div class="m-2"><%= link_to '編集', edit_admin_category_path(category.id), class: "btn btn-outline-primary" %></div>
          <div class="m-2"><%= link_to '削除', admin_category_path(category.id), class: "btn btn-outline-danger", method: :delete, "data-confirm" => "本当に削除しますか？"  %></div>
        </div>
      <% end %>
    </div>
  </div>
</div>