config/routes.rb
Rails.application.routes.draw do

 # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
 
 namespace :admin do
    get '/' => 'homes#top'
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :categories, only: [:index, :create, :edit, :update, :destroy]
    resources :users, only: [:show, :edit, :update, :destroy]
    resources :posts, only: [:show, :destroy] do
      resources :reviews, only: [:index, :destroy]
    end
    
    get 'search' => 'searches#search'
  end
  
 # 会員用
  devise_for :user, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :user do
    post 'user/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  
  scope module: :public do
    root to: 'homes#top'  
    resources :posts, only: [:new, :index, :show, :edit, :create, :update, :destroy] do
      resource :likes, only: [:create, :destroy]
      resources :reviews, only: [:new, :index, :create], shallow: true do
        resource :favorite, only: [:create, :destroy]
      end
      resources :reviews, only: [:edit, :update, :destroy]
    end 
    
    resources :retirements, only: [:new, :destroy]
    resources :users, except: [:show, :edit, :update] do
      member do
        get :likes
      end
    end
    
    get 'search' => 'searches#search'
    get '/:name' => 'users#show' 
    get '/:name/edit' => 'users#edit'
    patch '/:name' => 'users#update'
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :post_categories, dependent: :destroy
  has_many :posts, through: :post_categories, dependent: :destroy
  
  validates :name, uniqueness: true, length: { in: 1..30 }
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :review
  
  validates :user_id, uniqueness: {scope: :review_id}
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :post_genres, dependent: :destroy
  has_many :posts, through: :post_genres, dependent: :destroy
  
  validates :name, uniqueness: true, length: { in: 1..30 }
  
end

app/models/like.rb
class Like < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  
  validates :user_id, uniqueness: {scope: :post_id}
  
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_genres, dependent: :destroy
  has_many :genres, through: :post_genres, dependent: :destroy
  has_many :post_categories, dependent: :destroy
  has_many :categories, through: :post_categories, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  has_one_attached :post_image

  def get_post_image(width, height)
    unless post_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      post_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    post_image.variant(resize_to_limit: [width, height]).processed
  end

  def liked_by?(user)
    likes.exists?(user_id: user.id)
  end

  validates :name, uniqueness: true, length: { in: 1..75 }
  validates :day, length: { in: 1..100 }
  validates :close_day, length: { in: 1..100 }
  validates :hour, length: { in: 1..100 }
  validates :place, length: { in: 1..75 }
  validates :address, length: { in: 1..100 }
  validates :body, length: { in: 1..750 }
  validates :url, length: { in: 1..100 }
  validates :genre_id, acceptance: true
  validates :category_id, acceptance: true

  # 検索方法分岐
  def self.looks(word, method)
    if method == "partial_match"
      @post = Post.where(["name LIKE(?) OR day LIKE(?)","%#{word}%", "%#{word}%"])
    elsif method == "perfect_match"
      @post = Post.where(["name LIKE(?) OR day LIKE(?)","#{word}", "#{word}"])
    elsif method == "forward_match"
      @post = Post.where(["name LIKE(?) OR day LIKE(?)","#{word}%", "#{word}%"])
    elsif method == "backward_match"
      @post = Post.where(["name LIKE(?) OR day LIKE(?)","%#{word}", "%#{word}"])
    else
      @post = Post.all
    end
  end

  # 並べ替え
  scope :latest, -> { order(created_at: :desc) }
  scope :old, -> { order(created_at: :asc) }
  scope :liked, -> {
    select('posts.*, COUNT(likes.id) AS likes_count')
      .left_joins(:likes)
      .group('posts.id')
      .order('likes_count DESC')
  }

end

app/models/post_category.rb
class PostCategory < ApplicationRecord
  belongs_to :post
  belongs_to :category
end

app/models/post_genre.rb
class PostGenre < ApplicationRecord
  belongs_to :post
  belongs_to :genre
end

app/models/review.rb
class Review < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  
  enum day: { ordinary: 0, weekend: 1, ordinary_limit: 2, weekend_limit: 3 }
  enum time: { open: 0, am: 1, noon: 2, afternoon: 3, early_evening: 4, evening: 5 }
  enum congestion: { empty: 0, full: 1, admission_limit_bit: 2, admission_limit: 3, admission_limit_many: 4 }
  
  validates :title, length: { in: 1..50 }
  validates :body, length: { in: 10..500 }
  validates :rate, presence: true
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end  
    
  # 並べ替え
  scope :latest, -> { order(created_at: :desc) }
  scope :old, -> { order(created_at: :asc) }
  scope :favorited, -> {
    select('reviews.*, COUNT(favorites.id) AS favorites_count')
      .left_joins(:favorites)
      .group('reviews.id')
      .order('favorites_count DESC')
  }
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :posts, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :review

  validates :name, presence: true, uniqueness: true, format: { with: /\A[a-zA-Z0-9]+\z/ }
  validates :introduction, length: { maximum: 300 }

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  #ゲストログイン
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guest"
    end
  end

  # 検索方法分岐
  def self.looks(word, method)
    if method == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    elsif method == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif method == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif method == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    else
      @user = User.all
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_alert(key)
    case key
    when "alert"
      "danger"
    when "notice"
      "success"
    when "error"
      "warning"
    end
  end
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_search.html.erb
<div class="search_form">
  <% if admin_signed_in? %>
    <%= form_with url: admin_search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['展覧会名/開催日','Post'], ['ユーザー','User']]) %>
      <%= f.select :method, options_for_select([["部分一致","partial_match"], ["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"]]) %>
      <%= f.submit "検索", class: "btn-sm btn-primary" %>
    <% end %>
  <% else %>
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['展覧会名/開催','Post'], ['ユーザー','User']]) %>
      <%= f.select :method, options_for_select([["部分一致","partial_match"], ["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"]]) %>
      <%= f.submit "検索", class: "btn-sm btn-primary" %>
    <% end %>
  <% end %>  
</div>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Momiji</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

　　<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/76fba6016b.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body class="d-flex flex-column vh-100" style="background-color: #f8f4e6;" data-turbolinks='false'>
 
      <nav  class="navbar fixed-top navbar-expand-lg navbar-light shadow-sm"  style="background-color: #eb6101;">
        <div class="container-fluid">
        <a class="navbar-brand" href="/">
           <%= image_tag "logo-003.png" %>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"> 
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'マイページ', "/#{current_user.name}", class: 'nav-link text-light' %> 
            </li>
            <li class="nav-item">
              <%= link_to "展覧会情報", posts_path, class: 'nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "新規投稿(展覧会)", new_post_path, class: 'nav-link text-light' %>
            </li>  
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-light' %>
            </li>  
      
            <% elsif admin_signed_in? %>
            <li class="nav-item">
              <%= link_to "展覧会情報", posts_path, class: 'nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "ユーザー", admin_path, class: 'nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "ジャンル作成/一覧", admin_genres_path, class: 'nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "カテゴリー作成/一覧", admin_categories_path, class: 'nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト",  destroy_admin_session_path, method: :delete, class: 'nav-link text-light' %>
            </li>
        
            <% else %>
            <li class="nav-item">
              <%= link_to "展覧会情報", posts_path, class: 'nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to 'ゲストログイン（閲覧用）', user_guest_sign_in_path, method: :post, class: 'nav-link text-light' %>
            </li>  
            <% end %>  
          </ul>
        </div>
        </div>
      </nav>
    
      <main class="m-3 pt-5">
      
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= bootstrap_alert(key) %>" role="alert">
          <strong><%= value %></strong>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
      
      <%= yield %>

    </main>
    
    <footer class="footer mt-auto py-3" style="background-color: #a99e93;">
      <div class="container mt-3">
        <div class="row">
           <div class="d-flex justify-content-center">
            <p>momiji.shimashima</p>
          </div>
        </div>  
      </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>